# Generated by Django 2.1.4 on 2018-12-29 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField()),
                ('i_level', models.CharField(max_length=255)),
                ('required_level', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('drop_rate', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('image', models.TextField(blank=True)),
                ('level', models.CharField(max_length=2)),
                ('health', models.CharField(blank=True, max_length=255)),
                ('damage', models.CharField(blank=True, max_length=255)),
                ('armor', models.CharField(blank=True, max_length=255)),
                ('model_id', models.CharField(blank=True, max_length=255)),
                ('faction', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.CharField(blank=True, max_length=255)),
                ('websites_id', models.CharField(blank=True, max_length=10)),
                ('items', models.ManyToManyField(blank=True, to='backend.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mob',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Zone'),
        ),
    ]
