# Generated by Django 2.1.4 on 2019-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
