# Generated by Django 2.2 on 2019-04-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181229_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mob',
            old_name='items',
            new_name='item',
        ),
    ]
