# Generated by Django 2.1.4 on 2019-05-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190430_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mob',
            old_name='item',
            new_name='items',
        ),
    ]
