# Generated by Django 2.1.4 on 2019-05-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190503_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mob',
            name='x_coordinate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mob',
            name='y_coordinate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
